//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncubatorData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public int Id { get; set; }
        public int CompanyStatus { get; set; }
        public string CompanyName { get; set; }
        public string ManagingPartner { get; set; }
        public int LaunchedYear { get; set; }
        public int Stage { get; set; }
        public int NumberOfMembers { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int Pincode { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual StageDetail StageDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
